domain: frostbit.in
tunnel_name: k8s-cluster-tunnel
gateways:
  router:
    name: router
    endpoint: 10.10.101.1
    port: 80
    backend_protocol: http
    namespace: default
  adguard:
    name: adguard
    endpoint: 10.10.101.1
    port: 8080
    backend_protocol: http
    namespace: default
  octopi:
    name: octopi
    endpoint: 10.10.101.200
    port: 80
    backend_protocol: http
    namespace: default
  hubble:
    name: hubble
    endpoint: hubble-ui.kube-system.svc.cluster.local
    port: 80
    backend_protocol: http
    namespace: kube-system
  unifi:
    name: unifi
    endpoint: service.unifi.svc.cluster.local
    port: 8443
    backend_protocol: https
    namespace: unifi
  kube:
    name: kube
    endpoint: kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc.cluster.local
    port: 443
    backend_protocol: https
    namespace: kubernetes-dashboard
  c30:
    name: c30
    endpoint: 10.10.101.249
    port: 8006
    backend_protocol: https
    namespace: default




