apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: librenms
  name: librenms
---

apiVersion: v1
data:
  api-token: aGVsbG8NCg==
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/cloudflare-api-token-secret
  labels:
    app: librenms
  name: cloudflare-api-token-secret
  namespace: librenms
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: librenms
    service-type: internal
  name: service
  namespace: librenms
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: librenms
    port: 8000
    targetPort: 8000
  selector:
    app: librenms
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: librenms
  name: nfs-librenms
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2000Gi
  nfs:
    path: /nfsshare/apps/librenms
    server: 10.10.101.210
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: librenms
  name: nfs-librenms-db
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2000Gi
  nfs:
    path: /nfsshare/apps/librenms-db
    server: 10.10.101.210
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: librenms
  name: nfs
  namespace: librenms
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-librenms
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: librenms
  name: nfs-librenms-db
  namespace: librenms
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-librenms-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: librenms
  name: deploy
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms
  template:
    metadata:
      labels:
        app: librenms
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PASSWORD
          value: librenms
        - name: REDIS_HOST
          value: 127.0.0.1
        image: librenms/librenms
        name: container
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /data
          name: persist
          readOnly: false
      - env:
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PASSWORD
          value: librenms
        - name: SIDECAR_DISPATCHER
          value: "1"
        - name: REDIS_HOST           
          value: 127.0.0.1
        image: librenms/librenms
        name: dispatcher
        volumeMounts:
        - mountPath: /data
          name: persist
          readOnly: false
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: librenms
        - name: MYSQL_DATABASE
          value: librenms
        - name: MYSQL_USER
          value: librenms
        - name: MYSQL_PASSWORD
          value: librenms
        image: mariadb
        name: librenms-db
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: persist-db
      - image: redis
        name: librenms-redis
        ports:
        - containerPort: 6379
      volumes:
      - name: persist
        persistentVolumeClaim:
          claimName: nfs
      - name: persist-db
        persistentVolumeClaim:
          claimName: nfs-librenms-db
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
  labels:
    app: librenms
  name: gateway
  namespace: librenms
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: librenms.frostbit.in
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http-librenms
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: librenms.frostbit.in
    name: https-librenms
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: secret-tls-librenms
      mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app: librenms
  name: route
  namespace: librenms
spec:
  parentRefs:
  - name: gateway
    namespace: librenms
  rules:
  - backendRefs:
    - name: service
      port: 8000
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  labels:
    app: librenms
  name: tunnel
  namespace: librenms
subjects:
- name: cilium-gateway-gateway
  spec:
    fqdn: librenms.frostbit.in
    target: http://cilium-gateway-gateway.librenms.svc.cluster.local:80
tunnelRef:
  kind: ClusterTunnel
  name: k8s-cluster-tunnel
