apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: ollama
  name: ollama
---


apiVersion: v1
data:
  api-token: aGVsbG8NCg==
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/cloudflare-api-token-secret
  labels:
    app: ollama
  name: cloudflare-api-token-secret
  namespace: ollama
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
    service-type: internal
  name: service
  namespace: ollama
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: ollama
    port: 11434
    targetPort: 11434
  selector:
    app: ollama
  type: LoadBalancer
---


apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: ollama
  name: nfs-ollama
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2000Gi
  nfs:
    path: /nfsshare/apps/ollama
    server: 10.10.101.210
---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ollama
  name: nfs
  namespace: ollama
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-ollama
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ollama
  name: deploy
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - image: ollama/ollama
        name: container
        ports:
        - containerPort: 11434
        volumeMounts:
        - mountPath: /root/.ollama
          name: persist
          readOnly: false
      volumes:
      - name: persist
        persistentVolumeClaim:
          claimName: nfs
---


