proxmox_username  = "root@pam"
proxmox_password  = "password"
proxmox_api_url   = "https://10.10.101.250:8006/api2/json"
proxmox_node      = "proxiemoxie"
kube_version      = "1.30"
ssh_pass_hash     = "$6$lgaVEaws0B$YsuEPd4sw5bTXnEpTloZAB2kSaVn.IdQ2dWHMjlgRh/KPg8fcZn0mAiiP4lolcBsT3pkQVTBYBWJ6Zp3CRTte/"